#!/usr/bin/perl

=pod Profiling statements
#!/usr/bin/perl -d:NYTProf
$ENV{'NYTPROF'}="trace=2:start=init:file=/tmp/interactomProf.out";
=cut

use strict;
use vars qw/$DB $URL %EQUIV/;

use warnings;
use diagnostics;

use lib qw(lib/perl);

#from CPAN
use CGI;
use Ace 1.51;

use JSON;
use Data::Dumper;
use Log::Log4perl qw(get_logger :levels);
#custom
use common;
use newPort;

our $DEV_STATUS = 'TEST';


Log::Log4perl->init("./conf/newPort.conf");
my $logger = get_logger();

$logger->info("*** CGI activation at " . common::getTime());
our $DB = Ace->connect(-host  => 'localhost', -port  => 55555)  ||
  $logger->logdie("Couldn't open database");

#our $DB = Ace->connect(-path=>'/home/matrixdb/matrixdb_latest') || die "couldnot connect to DB";

my $query = CGI->new();
$logger->info(Dumper( $query ));
my $data = newPort::getData({
			     type => $query->{ type }->[0],
			     value => $query->{ value }->[0],
			     DB => $DB
			    });
$logger->trace(Dumper( $data ));
my $jsonString = encode_json($data);
open LOG, ">/tmp/reportLatest.json";
print LOG "$jsonString\n";
close LOG;

my $urlRoot = $DEV_STATUS eq "TEST" ? "http://matrixdb.ibcp.fr:9999" : "http://matrixdb-new.ibcp.fr";

my $customJSlib = {
		   experiment => "<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/GLMOL/Three49custom.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/GLMOL/GLmol.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/jquery.hoverIntent.minified.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/js/molecularViewer.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/js/utils.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/js/elementInfo.js\"></script>",
		   biomolecule => "<script type=\"text/javascript\" src=\"$urlRoot/js/barChart.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/js/elementInfo.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/js/molecularViewer.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/GLMOL/Three49custom.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/GLMOL/GLmol.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/jquery.hoverIntent.minified.js\"></script>" .
		   "<script type=\"text/javascript\" src=\"$urlRoot/js/utils.js\"></script>"
};

my $customCSSlib = { biomolecule =>  "<link rel=\"stylesheet\" href=\"$urlRoot/css/molecularViewer.css\"/>" .
		     "<link rel=\"stylesheet\" href=\"$urlRoot/css/elementInfo.css\"/>",
		     experiment =>  "<link rel=\"stylesheet\" href=\"$urlRoot/css/molecularViewer.css\"/>" .
		     "<link rel=\"stylesheet\" href=\"$urlRoot/css/elementInfo.css\"/>"
		   };

my $htmlContent = 
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">" .
"<html lang=\"en-US\" xml:lang=\"en-US\" xmlns=\"http://www.w3.org/1999/xhtml\">".
"<head><meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=windows-1252\"/>" .
"<link rel=\"stylesheet\" href=\"$urlRoot/dependencies/css/bootstrap.min.css\"/>" .
"<link href=\"//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\" rel=\"stylesheet\">" .
"<link rel=\"stylesheet\" href=\"$urlRoot/css/report.css\"/>" .
"<link rel=\"stylesheet\" href=\"$urlRoot/css/cart.css\"/>" .
"<link rel=\"stylesheet\" type=\"text/css\" href=\"http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css\">" .
"<script src=\"http://code.jquery.com/jquery-1.10.1.min.js\"></script>" .
"<script src=\"http://d3js.org/d3.v3.min.js\"></script>" .
"<script type=\"text/javascript\" charset=\"utf8\" src=\"http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js\"></script>" .
"<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/bootstrap.js\"></script>" .
"<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/bootstrapExtDatatable.js\"></script>" .
"<script type=\"text/javascript\" src=\"$urlRoot/dependencies/js/jquery.cookie.js\"></script>" .
"<script type=\"text/javascript\" src=\"$urlRoot/js/reportMaestro.js\"></script>" .
"<script type=\"text/javascript\" src=\"$urlRoot/js/report.js\"></script>" .
"<script type=\"text/javascript\" src=\"$urlRoot/js/cart.js\"></script>";
my $htmlTrailer = "<script type=\"text/javascript\">" .  '$(function(){'  . "runReportMaestro({rootUrl:\"$urlRoot\", cart : true, reportDiv : \"#reportDiv\", jsonData : " . $jsonString . "})})</script>" .
  "<title>MatrixDB report</title></head><body><div id = \"reportDiv\"></div></body><div id=\'bodyFooter\'></div></html>\n";

$htmlContent .= defined ($customJSlib->{ $query->{ type }->[0] }) 
  ? $customJSlib->{ $query->{ type }->[0] } : '';
$htmlContent .= defined ($customCSSlib->{ $query->{ type }->[0] }) 
  ? $customCSSlib->{ $query->{ type }->[0] } : '';

$logger->info ("HTML content:\n" . $htmlContent . $htmlTrailer);
print $query->header;
print "$htmlContent$htmlTrailer\n";

