#!/usr/bin/perl
use strict;
use vars qw/$DB $URL %EQUIV/;

use warnings;
use diagnostics;

use lib ("$ENV{ IDN_LIB }/perl");

#from CPAN
use CGI;
use Ace 1.51;
use JSON;
use Data::Dumper;
use Log::Log4perl qw(get_logger :levels);
#custom
use common;
Log::Log4perl->init("$ENV{ IDN_CONF }/statistic.conf");
my $logger = get_logger();
my $query = CGI->new();

my $dataContainer = {
		  associations => {
				  total => [],
				  protein => [],
				  fragment => [],
				  multimer => [],
				  glycosaminoglycan => [],
				  cation => [],
				  lipid => [],
				  inorganic => [],
				  synthetic => []
				 },
		  interactions => {
				   matrixdb => [0,0],
				   psicquic => [0,0]
				  },
		  publications => { total => 0, imex => 0 }
		 };


our $DB = Ace->connect(-host  => 'localhost', -port  => 55555)  || 
  $logger->error ("Couldn't open database");

#molecular interactions data
my $r = $DB->raw_query('find association matrixdb and genuine');
if ($r =~ /Found ([\d]+) object/) {
  $dataContainer->{ interactions }->{ matrixdb }->[0] = $1;
}

my $r = $DB->raw_query('find experiment matrixdb');
if ($r =~ /Found ([\d]+) object/) {
  $dataContainer->{ interactions }->{ matrixdb }->[1] = $1;
}

my $r = $DB->raw_query('find association genuine');
if ($r =~ /Found ([\d]+) object/) {
  $dataContainer->{ interactions }->{ psicquic }->[0] = $1;
}

my $r = $DB->raw_query('find experiment');
if ($r =~ /Found ([\d]+) object/) {
  $dataContainer->{ interactions }->{ psicquic }->[1] = $1;
}


#Publications
$DB->raw_query('query find experiment matrixdb where imex_id_experiment');
$r = $DB->raw_query('follow PMID');
if ($r =~ /Found ([\d]+) object/) {
  $dataContainer->{ publications }->{ imex } = $1;
}

my $r = $DB->raw_query('find publication association');
if ($r =~ /Found ([\d]+) object/) {
  $dataContainer->{ publications }->{ total } = $1;
}


print $query->header('application/json');      # create the HTTP header





























